steps:
- name: node
  id: build tests
  entrypoint: npm
  args:
  - 'install'

- name: node
  id: run development environment tests
  entrypoint: npm
  args:
  - 'run'
  - 'test-dev'

 # This step deploys the stage application in Kubernetes
- name: 'gcr.io/cloud-builders/gcloud'
  id: Start Stage Deployment
  args:
  - builds
  - submit
  - --config
  - cloudbuild-stage.yaml
  - --substitutions
  - _SHORT_SHA=$TRACE_TOKEN
  - .